version: '3.1'

services:

  api:
    build:
      context: ./api_module
    image: api
    ports:
      - "5010:5010"
    volumes:
      - ./api_module/.:/app

  flask-app:
    image: flask-app
    build: ./dashboard_module/Interface-web
    ports:
      - 5020:5020
    volumes:
      - ./dashboard_module/Interface-web/app/.:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


  coap:
    build:
      context: ./iot_module/coap
      dockerfile: Dockerfile
    container_name: coap
  

  publisher:
    build:
      context: ./iot_module/publisher
      dockerfile: Dockerfile
    container_name: mqtt_publisher

  subscriber:
    build:
      context: ./iot_module/subscriber
      dockerfile: Dockerfile
    container_name: mqtt_subscriber