version: '3.1'

services:

  api:
    build:
      context: ./api_module
    image: api
    ports:
      - "5010:5010"
    volumes:
      - ./api_module/.:/app

  dashboard:
    build:
      context: ./dashboard_module
    image: dashboard
    ports:
      - "5020:5020"
    volumes:
      - ./dashboard_module/.:/app

  iot:
    build:
      context: ./iot_module
    image: iot
    ports:
      - "5030:5030"
    volumes:
      - ./iot_module/.:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/