version: '3.7'

services:
  flask-app:
    image: flask-app
    build: ./dashboard_module/Interface-web
    ports:
      - 5000:5000
    volumes:
      - ./dashboard_module/Interface-web/app/.:/app
  mongo:
    build:
      context: ./dashboard_module/mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"